-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgKKM96qxqqtQsEuyX
Y7BK/jMBMORUNujbbDdFL9OFHm+gCgYIKoZIzj0DAQehRANCAATjyxNrA9lpvYAT
vry4CQKSEnrDc93YWDYiiPrwgeFRpnv++LysGKN/1L9FY+q4zFcqtxQo+OKs5WtG
nnF6CKEi
-----END PRIVATE KEY-----