# Generated by Django 5.1.6 on 2025-04-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_alter_category_description_alter_category_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
