# Generated by Django 5.1.6 on 2025-04-25 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0017_inwork'),
        ('clinic', '0014_clinic_description_clinic_latitude_clinic_longitude'),
        ('users', '0014_image'),
        ('utils', '0005_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('costumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.specialist')),
            ],
        ),
    ]
