# Generated by Django 5.0.14 on 2025-09-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_story_storyview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
