# Generated by Django 5.1.6 on 2025-04-18 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic', '0004_alter_commentreadmore_options_and_more'),
        ('users', '0010_weekday'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.specialist')),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.weekday')),
            ],
        ),
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.specialist')),
                ('worktime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.worktime')),
            ],
        ),
    ]
