# Generated by Django 5.1.6 on 2025-04-22 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0012_remove_specialist_service'),
        ('service', '0004_alter_worktime_date'),
        ('utils', '0005_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.specialist')),
            ],
        ),
    ]
