# Generated by Django 5.1.6 on 2025-04-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='preparation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
