# Generated by Django 5.1.6 on 2025-05-01 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_service_description_service_preparation_service_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booked',
            name='worktime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.worktime'),
        ),
    ]
