# Generated by Django 5.1.6 on 2025-05-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_booked_date_alter_booked_worktime'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='finish',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
