# Generated by Django 5.0.14 on 2025-05-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_worktime_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('process', 'process'), ('reject', 'reject')], default='active', max_length=10),
        ),
    ]
