# Generated by Django 5.0.14 on 2025-06-14 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0033_alter_worker_status'),
        ('clinic', '0019_alter_comment_author'),
        ('service', '0009_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic'),
        ),
        migrations.AlterField(
            model_name='worktime',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.specialist'),
        ),
    ]
