# Generated by Django 5.0.14 on 2025-09-23 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0039_alter_specialist_gen'),
        ('service', '0010_worktime_clinic_alter_worktime_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktime',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worktime_specialist', to='basic.specialist'),
        ),
    ]
