# Generated by Django 5.1.6 on 2025-03-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patient_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='c_lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='c_lon',
            new_name='longitude',
        ),
    ]
