# Generated by Django 5.1.6 on 2025-04-26 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_typeclinic_clinic_types'),
        ('users', '0016_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic'),
        ),
    ]
