# Generated by Django 5.1.6 on 2025-04-26 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_address_lat_alter_address_lng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnkita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/')),
            ],
        ),
        migrations.AlterField(
            model_name='ankita',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ankita',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.imageankita'),
        ),
    ]
