# Generated by Django 5.1.6 on 2025-04-26 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_imageankita_alter_ankita_phone_ankita_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ankita',
            name='image',
        ),
    ]
