# Generated by Django 5.1.6 on 2025-04-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_ankita_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ankita',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ankita',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ankita',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
