# Generated by Django 5.0.14 on 2025-05-26 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_chatdoctor_messagedoctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ankita',
            name='relative_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ankita',
            name='relative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.relative'),
        ),
    ]
