# Generated by Django 5.0.14 on 2025-05-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_ankita_relative_text_alter_ankita_relative'),
    ]

    operations = [
        migrations.AddField(
            model_name='ankita',
            name='waist',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
