# Generated by Django 5.0.14 on 2025-09-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expire',
            field=models.CharField(max_length=100),
        ),
    ]
