# Generated by Django 5.1.6 on 2025-04-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_created_at_order_datetime_order_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
