# Generated by Django 5.1.6 on 2025-04-26 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_payment_type'),
        ('service', '0006_service_description_service_preparation_service_time'),
        ('users', '0015_relative_ankita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='ankita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ankita'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='service.service'),
        ),
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.image'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.phone'),
        ),
    ]
