# Generated by Django 5.1.6 on 2025-04-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_phone_order_ankita_order_service_alter_order_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='order.orderfile'),
        ),
    ]
