# Generated by Django 5.1.6 on 2025-04-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderfile_remove_order_image_order_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.ManyToManyField(blank=True, null=True, to='order.phone'),
        ),
    ]
