# Generated by Django 5.1.6 on 2025-04-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_phone_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='file',
        ),
    ]
