# Generated by Django 5.1.6 on 2025-04-30 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0018_remove_symptomsubtype_category_symptomtype_category'),
        ('order', '0010_order_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic'),
        ),
    ]
