# Generated by Django 5.1.6 on 2025-05-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('wait', 'wait'), ('active', 'active'), ('inactive', 'inactive'), ('cancellation', 'cancellation')], default='wait', max_length=20),
        ),
    ]
