# Generated by Django 5.1.6 on 2025-02-11 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadMore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_prices', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('education', models.CharField(max_length=100)),
                ('qualifications', models.CharField(max_length=100)),
                ('associations', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CommentReadMore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('service_rendered', models.DateField(blank=True, null=True)),
                ('experts_response', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('read_more', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.readmore')),
            ],
        ),
        migrations.CreateModel(
            name='Specialists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('nurses', 'nurses'), ('doctor', 'doctor')], max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='specialists/%Y/%m/%d/')),
                ('experience', models.IntegerField(default=0)),
                ('type_service', models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('night', 'night')], max_length=100)),
                ('category', models.ManyToManyField(blank=True, to='utils.category')),
                ('staff', models.ManyToManyField(to='clinic.clinic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='readmore',
            name='specialists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.specialists'),
        ),
        migrations.CreateModel(
            name='OpinioColleagues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('read_more', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.readmore')),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.specialists')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='story/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
