# Generated by Django 5.1.6 on 2025-02-12 12:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
        ('clinic', '0003_rename_photos_photo'),
        ('utils', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpinioColleagues',
            new_name='OpinioColleague',
        ),
        migrations.RenameModel(
            old_name='Specialists',
            new_name='Specialist',
        ),
    ]
