# Generated by Django 5.1.6 on 2025-03-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_rename_opiniocolleagues_opiniocolleague_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpinioColleague',
            new_name='OpinionColleague',
        ),
    ]
