# Generated by Django 5.1.6 on 2025-03-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_rename_opiniocolleague_opinioncolleague'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentreadmore',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарий'},
        ),
        migrations.AlterModelOptions(
            name='opinioncolleague',
            options={'verbose_name': 'Мнение коллег', 'verbose_name_plural': 'Мнение коллег'},
        ),
        migrations.AlterModelOptions(
            name='readmore',
            options={'verbose_name': 'Читать далее', 'verbose_name_plural': 'Читать далее'},
        ),
        migrations.AlterModelOptions(
            name='specialist',
            options={'verbose_name': 'Специалисты', 'verbose_name_plural': 'Специалисты'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Истории', 'verbose_name_plural': 'Истории'},
        ),
    ]
