# Generated by Django 5.1.6 on 2025-04-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_alter_commentreadmore_options_and_more'),
        ('clinic', '0006_clinic_type_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='staff',
            field=models.ManyToManyField(blank=True, null=True, to='clinic.clinic'),
        ),
    ]
