# Generated by Django 5.1.6 on 2025-04-18 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_alter_specialist_staff'),
        ('utils', '0005_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='category',
        ),
        migrations.AddField(
            model_name='specialist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.category'),
        ),
    ]
