# Generated by Django 5.1.6 on 2025-04-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_remove_specialist_category_specialist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='service',
            field=models.IntegerField(default=0),
        ),
    ]
