# Generated by Django 5.1.6 on 2025-04-19 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_specialist_service'),
        ('users', '0011_alter_patient_pinfl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreadmore',
            name='read_more',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.specialist'),
        ),
        migrations.AlterField(
            model_name='commentreadmore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient'),
        ),
    ]
