# Generated by Django 5.1.6 on 2025-04-19 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_alter_commentreadmore_read_more_and_more'),
        ('utils', '0005_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.category')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.specialist')),
            ],
        ),
    ]
