# Generated by Django 5.1.6 on 2025-04-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_specialist_category_alter_specialist_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='service',
        ),
    ]
