# Generated by Django 5.1.6 on 2025-04-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0012_remove_specialist_service'),
        ('utils', '0005_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='category',
        ),
        migrations.AddField(
            model_name='specialist',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='utils.category'),
        ),
    ]
