# Generated by Django 5.1.6 on 2025-04-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0013_remove_specialist_category_specialist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
