# Generated by Django 5.1.6 on 2025-04-22 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0016_commentreadmore_created_at'),
        ('users', '0013_patient_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('finish', models.TimeField()),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.specialist')),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.weekday')),
            ],
        ),
    ]
