# Generated by Django 5.1.6 on 2025-04-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0017_inwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specialist',
            name='gen',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='specialist',
            name='pinfl',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='type',
            field=models.CharField(blank=True, choices=[('nurses', 'nurses'), ('doctor', 'doctor')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='type_service',
            field=models.CharField(blank=True, choices=[('online', 'online'), ('offline', 'offline'), ('night', 'night')], max_length=100, null=True),
        ),
    ]
