# Generated by Django 5.1.6 on 2025-05-01 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0019_specialist_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='education')),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_education', to='basic.education')),
            ],
        ),
    ]
