# Generated by Django 5.1.6 on 2025-05-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0021_work_workimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
