# Generated by Django 5.1.6 on 2025-05-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0022_specialist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
