# Generated by Django 5.1.6 on 2025-05-04 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0023_education_start_date'),
        ('order', '0012_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreadmore',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
