# Generated by Django 5.1.6 on 2025-05-04 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0024_commentreadmore_order'),
        ('users', '0027_chatdoctor_messagedoctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReadMoreComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.commentreadmore')),
            ],
        ),
        migrations.CreateModel(
            name='CommentReadMoreLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.commentreadmore')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
    ]
