# Generated by Django 5.1.6 on 2025-05-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0025_commentreadmorecomment_commentreadmorelike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='start_date',
            new_name='start',
        ),
        migrations.AlterField(
            model_name='education',
            name='type',
            field=models.CharField(max_length=125),
        ),
    ]
