# Generated by Django 5.1.6 on 2025-05-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0026_rename_start_date_education_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='finish',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
