# Generated by Django 5.1.6 on 2025-05-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0027_alter_education_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
