# Generated by Django 5.1.6 on 2025-05-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0028_work_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='finish',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
