# Generated by Django 5.0.14 on 2025-06-13 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0030_remove_work_category_alter_education_type_and_more'),
        ('clinic', '0019_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='type',
            field=models.CharField(blank=True, choices=[('nurses', 'nurses'), ('doctor', 'doctor'), ('clinic', 'clinic')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AdminClinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, choices=[('admin', 'admin'), ('director', 'director'), ('manager', 'manager'), ('sub_director', 'sub_director')], max_length=100, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('specialist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basic.specialist')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.specialist')),
            ],
        ),
    ]
