# Generated by Django 5.0.14 on 2025-06-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0031_alter_specialist_type_adminclinic_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminclinic',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='adminclinic',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
