# Generated by Django 5.0.14 on 2025-06-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0032_adminclinic_email_adminclinic_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('waiting', 'waiting'), ('rejected', 'rejected')], default='waiting', max_length=100),
        ),
    ]
