# Generated by Django 5.0.14 on 2025-06-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0035_payme_alter_balance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payme',
            name='state',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
