# Generated by Django 5.0.14 on 2025-06-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0036_payme_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='payme',
            name='reason',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
