# Generated by Django 5.0.14 on 2025-09-22 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0037_payme_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreadmore',
            name='read_more',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentreadmore', to='basic.specialist'),
        ),
        migrations.AlterField(
            model_name='inwork',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialistinwork', to='basic.specialist'),
        ),
    ]
