# Generated by Django 5.0.14 on 2025-09-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0038_alter_commentreadmore_read_more_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='gen',
            field=models.CharField(blank=True, choices=[('man', 'man'), ('woman', 'woman')], max_length=100),
        ),
    ]
