# Generated by Django 5.1.6 on 2025-03-10 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_rename_photos_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'verbose_name': 'Клиники', 'verbose_name_plural': 'Клиники'},
        ),
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name': 'Описания', 'verbose_name_plural': 'Описания'},
        ),
        migrations.AlterModelOptions(
            name='infoclinic',
            options={'verbose_name': 'Инфо о клиниках', 'verbose_name_plural': 'Инфо о клиниках'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуги', 'verbose_name_plural': 'Услуги'},
        ),
    ]
