# Generated by Django 5.1.6 on 2025-04-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_service_image_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='type',
            field=models.CharField(choices=[('clinic', 'clinic'), ('laboratories', 'laboratories'), ('diagnostic_centers', 'diagnostic_centers')], default='clinic', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
