# Generated by Django 5.1.6 on 2025-04-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_clinic_type_service_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={},
        ),
        migrations.AddField(
            model_name='clinic',
            name='category',
            field=models.CharField(choices=[('private', 'private'), ('state', 'state')], default='private', max_length=100),
        ),
    ]
