# Generated by Django 5.1.6 on 2025-04-22 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_alter_clinic_options_clinic_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.symptom')),
            ],
        ),
        migrations.CreateModel(
            name='SymptomSUbType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.symptomtype')),
            ],
        ),
    ]
