# Generated by Django 5.1.6 on 2025-04-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_symptom_symptomtype_symptomsubtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
