# Generated by Django 5.1.6 on 2025-04-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_symptom_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomtype',
            name='type',
            field=models.CharField(choices=[('review', 'Review'), ('reasons', 'Reasons'), ('treatment', 'Treatment'), ('treats', 'Treats')], max_length=100),
        ),
    ]
