# Generated by Django 5.1.6 on 2025-04-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_alter_symptomtype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptomtype',
            name='details',
        ),
    ]
