# Generated by Django 5.1.6 on 2025-04-22 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_remove_symptomtype_details'),
        ('utils', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='type',
            field=models.CharField(blank=True, choices=[('symptom', 'Symptom'), ('diagnoses', 'Diagnoses')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='symptomsubtype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.category'),
        ),
        migrations.AddField(
            model_name='symptomtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
