# Generated by Django 5.1.6 on 2025-04-23 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_symptom_type_symptomsubtype_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='image',
        ),
    ]
