# Generated by Django 5.0.14 on 2025-06-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0019_alter_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='preparation',
            new_name='name',
        ),
    ]
