# Generated by Django 5.0.14 on 2025-06-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0020_rename_preparation_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='preparation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
