# Generated by Django 5.0.14 on 2025-06-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0021_service_preparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('process', 'process'), ('reject', 'reject')], default='process', max_length=100, null=True),
        ),
    ]
