# Generated by Django 5.0.14 on 2025-09-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0022_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='symptom',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
